FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./

COPY . .

COPY entrypoint.sh .
RUN sed -i 's/\r$//g' entrypoint.sh && chmod +x entrypoint.sh

EXPOSE 5173

ENTRYPOINT ["./entrypoint.sh"]

CMD ["./node_modules/.bin/vite", "--host", "0.0.0.0"]
