version: '3.8'

services:
  file-manager:
    container_name: marufiles_app
    build:
      context: .
      args:
        VITE_MINIO_ENDPOINT: ${VITE_MINIO_ENDPOINT}
        VITE_MINIO_ACCESS_KEY: ${VITE_MINIO_ACCESS_KEY}
        VITE_MINIO_SECRET_KEY: ${VITE_MINIO_SECRET_KEY}
        VITE_MINIO_BUCKET_NAME: ${VITE_MINIO_BUCKET_NAME}

    ports:
      - "3000:3000"
