server {
    listen 80;

    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        # Esta línea es crucial para que el enrutamiento de React (react-router-dom) funcione.
        # Si no encuentra un archivo, redirige la petición a index.html
        try_files $uri $uri/ /index.html;
    }
}
